version: '3'
services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: javascript.dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - nginx
      - api

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  api:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - nginx
      - mysql

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '85:80'
      - '82:81'
      - '444:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
